# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'ExampleSwift' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
   use_frameworks!

  # Pods for TableViewCheck
	#pod 'PredictIO-iOS', '~> 0.5.0'
	pod 'PredictIO'
end
