platform :ios, '8.0'

target 'Example' do
  use_frameworks!

  # pod 'PredictIO/Swift4.0', path: '../'
  pod 'PredictIO/Swift4.0', git: "git@github.com:predict-io/PredictIO-iOS.git", branch: "sdk5"
end
